google_project_id       = "fuchicorp-gke-cluster"
google_bucket_name      = "fuchicorp-bucket-seil"
deployment_environment  = "qa"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json"